### ISSUE TITLE
Restart after 2023.11 update fails to import SERVICE_HOMEASSISTANT_RESTART

### ISSUE THREAD

**Issue by countertony** [tronikos/default_config_disabler#1]
On the restart at the end of an update to HA 2023.11 (and on subsequent restarts), the following error is generated in the log.

> Logger: homeassistant.setup
> Source: setup.py:215
> First occurred: 07:35:49 (1 occurrences)
> Last logged: 07:35:49
> 
> Setup failed for custom integration default_config_disabler: Unable to import component: cannot import name 'SERVICE_HOMEASSISTANT_RESTART' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
>     component = integration.get_component()
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 816, in get_component
>     ComponentProtocol, importlib.import_module(self.pkg_path)
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "/config/custom_components/default_config_disabler/__init__.py", line 7, in <module>
>     from homeassistant.const import SERVICE_HOMEASSISTANT_RESTART
> ImportError: cannot import name 'SERVICE_HOMEASSISTANT_RESTART' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

Full log attached at [home-assistant_2023-11-02T07-44-45.093Z.log](https://github.com/tronikos/default_config_disabler/files/13235757/home-assistant_2023-11-02T07-44-45.093Z.log)

System information attached at [system_information.txt](https://github.com/tronikos/default_config_disabler/files/13235797/system_information.txt) (Raspberry Pi 4)

**Comment by countertony** [comment]
Looking in the terminal, the directory `/usr/src` is not present

**Comment by tronikos** [comment]
Make sure you update to v0.0.2. I fixed this last week.

**Comment by countertony** [comment]
Whoops! Confirmed
