### ISSUE TITLE
Config flow could not be loaded: {"message":"Invalid handler specified"}

### ISSUE THREAD

**Issue by Korpip** [tronikos/default_config_disabler#4]
After installation I get this error when trying to load it in the devices screen.

Config flow could not be loaded: {"message":"Invalid handler specified"}

**Comment by tronikos** [comment]
Which version of HA? Anything in the logs?

**Comment by Korpip** [comment]
Core
2024.3.3
Frontend
20240307.0

**Comment by tronikos** [comment]
Can you try downgrading this component to v0.0.2 or upgrading Core to at least 2024.4.0?

**Comment by Korpip** [comment]
Downgrading worked.
I am running HA via Dietpi.
The update script is not moving to the latest version.

Thank you.
