### ISSUE TITLE
asynchronous file operations needed

### ISSUE THREAD

**Issue by Fullmono** [tronikos/default_config_disabler#5]
Hi, 

The following log appear in my journal :-)
I just follow the log instructions by creating an issue here...

`
Detected blocking call to open inside the event loop by custom integration 'default_config_disabler' at custom_components/default_config_disabler/helpers.py, line 38: with open(DEFAULT_CONFIG_MANIFEST_ORIGINAL, encoding="utf-8") as f: (offender: /mnt/dietpi_userdata/homeassistant/custom_components/default_config_disabler/helpers.py, line 38: with open(DEFAULT_CONFIG_MANIFEST_ORIGINAL, encoding="utf-8") as f:), please create a bug report at https://github.com/tronikos/default_config_disabler/issues Traceback (most recent call last): File "/home/homeassistant/.pyenv/versions/3.12.3/bin/hass", line 8, in <module> sys.exit(main()) File "/home/homeassistant/.pyenv/versions/3.12.3/lib/python3.12/site-packages/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/home/homeassistant/.pyenv/versions/3.12.3/lib/python3.12/site-packages/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/home/homeassistant/.pyenv/versions/3.12.3/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/home/homeassistant/.pyenv/versions/3.12.3/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/home/homeassistant/.pyenv/versions/3.12.3/lib/python3.12/asyncio/base_events.py", line 1987, in _run_once handle._run() File "/home/homeassistant/.pyenv/versions/3.12.3/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/home/homeassistant/.pyenv/versions/3.12.3/lib/python3.12/site-packages/homeassistant/setup.py", line 165, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/home/homeassistant/.pyenv/versions/3.12.3/lib/python3.12/site-packages/homeassistant/setup.py", line 447, in _async_setup_component await asyncio.gather( File "/home/homeassistant/.pyenv/versions/3.12.3/lib/python3.12/site-packages/homeassistant/setup.py", line 449, in <genexpr> create_eager_task( File "/home/homeassistant/.pyenv/versions/3.12.3/lib/python3.12/site-packages/homeassistant/util/async_.py", line 37, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/home/homeassistant/.pyenv/versions/3.12.3/lib/python3.12/site-packages/homeassistant/config_entries.py", line 742, in async_setup_locked await self.async_setup(hass, integration=integration) File "/home/homeassistant/.pyenv/versions/3.12.3/lib/python3.12/site-packages/homeassistant/config_entries.py", line 594, in async_setup result = await component.async_setup_entry(hass, self) File "/mnt/dietpi_userdata/homeassistant/custom_components/default_config_disabler/__init__.py", line 27, in async_setup_entry new_manifest = load_original_default_config_manifest() File "/mnt/dietpi_userdata/homeassistant/custom_components/default_config_disabler/helpers.py", line 38, in load_original_default_config_manifest with open(DEFAULT_CONFIG_MANIFEST_ORIGINAL, encoding="utf-8") as f:
Detected blocking call to open inside the event loop by custom integration 'default_config_disabler' at custom_components/default_config_disabler/helpers.py, line 44: with open(DEFAULT_CONFIG_MANIFEST, encoding="utf-8") as f: (offender:
`

**Cause**
The open call is synchronous and is being executed in the asynchronous event loop. This causes the event loop to be blocked until the file operation is completed, which is not efficient and can lead to performance issues.

**Solution**
To fix this, you need to perform file I/O operations in an asynchronous manner. You can use aiofiles, an asynchronous file operations library, to avoid blocking the event loop.

**My setup**
Home assistant Core v2024.6.0

**Comment by tronikos** [comment]
Fixed in v0.0.4
