### ISSUE TITLE
2024.8.0 can't disable conversation

### ISSUE THREAD

**Issue by PhantomPhoton** [tronikos/default_config_disabler#6]
Howdy,

I'm running 2024.8.0 and I have conversation set to disable, however, it's still enabled. I don't see anything in the logs indicating why it would fail.

please let me know if there's anything else I can provide.

**Comment by tronikos** [comment]
Was it working on a previous version? Do you have any of the integrations that depend on conversation? 
![image](https://github.com/user-attachments/assets/20cb9bed-801c-493c-ba91-91853856dc18)

**Comment by PhantomPhoton** [comment]
This was my first try, so I don't know if it worked previously, but I am running the mobile_app integration, so I guess that means it's forced enabled :( 

Apologies for the incorrect report.
